### PR TITLE
Build docs through sphinx docker image.

### PR DESCRIPTION
**Pull request by nolan-veed**
# Why

For https://github.com/roc-streaming/roc-toolkit/issues/561

# What

* Copied over the docker.sh script from main repo.
* Updated the workflow to build using docker image.

### CODE REVIEW

**Comment by nolan-veed** [comment]
Question: Should we use actions/checkout@v4 to git clone the roc-streaming.git repo, instead of doing it by `git clone` command?

This also has the side-effect of doing a shallow-clone, which is the default.

**Comment by gavv** [comment]
Thanks for PR.

> Question: Should we use actions/checkout@v4 to git clone the roc-streaming.git repo, instead of doing it by git clone command?

Why not. I think shallow clone is fine.

> Copied over the docker.sh script from main repo.

I think we can just copy command from script directly into build.yaml. In main repo, the script exists because it's invoked many times, but here we have only one invocation. Also I think `-e CI` and `--cap-add SYS_PTRACE` are not needed here.

Maybe we can even replace it with [this](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container), but I'm didn't test it.

**Comment by nolan-veed** [comment]
> > Copied over the docker.sh script from main repo.
> 
> I think we can just copy command from script directly into build.yaml. In main repo, the script exists because it's invoked many times, but here we have only one invocation. Also I think `-e CI` and `--cap-add SYS_PTRACE` are not needed here.

Sorry. I misread your message on the ticket - I thought you wanted the script copied for future purposes.

> 
> Maybe we can even replace it with [this](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container), but I'm didn't test it.

That looks tricky, since the whole job (all the steps) is for the container. If we split the job (which are parallel by default), then we need more code to make them sequential.

So, I'll leave this as s docker command for now.

**Comment by gavv** [comment]
LGTM!

**Comment by gavv** [comment]
https://github.com/roc-streaming/roc-streaming.github.io/commit/de259357d45610a0834022bd3044e40465a27748
https://github.com/roc-streaming/roc-streaming.github.io/commit/548651e3dcdf9541cb4647ed715a0d5068071421
https://github.com/roc-streaming/roc-streaming.github.io/actions/runs/6797937795/job/18481096787
https://github.com/roc-streaming/roc-streaming.github.io/actions/runs/6797957890
https://roc-streaming.org/toolkit/docs/

**Pull request merged**
